config/routes.rb
Rails.application.routes.draw do
	root to: "pages#index"

	resources :users

	get "/login", to: "users#login"
	post "/logresult", to: "users#logresult"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	validates :firstname, :lastname, :email, :password, :country, :city, :hous_number, presence: true
	validates :email, uniqueness: true
	validates :password, length: { in: 3..6 }
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
	    message: "Check yours email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def login
  end

  def logresult 
  	pp params[:user][:email]
  	@user = User.find_by_email_and_password(params[:user][:email], params[:user][:password])
  	if @user!=nil
  		session[:user] = @user.id
  		redirect_to user_path(@user.id)
  	end
  end

  def show
  	@user = User.find(session[:user])
  end

  def destroy
  	@user = User.find(session[:user])
    session[:user] = nil
    redirect_to root_path
  end


 private 

  def user_params 
  	params.require(:user).permit(:lastname, :firstname, :email, :password, :country, :city, :hous_number)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timelime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>My site</h1>
</br>
<p>I`m in app/views/pages/index.html.erb</p>
<%= link_to "Registration   ", new_user_path %> or <%= link_to "   Login   ", login_path%>

app/views/users/login.html.erb
<%= form_for :user, url: logresult_path do |f| %>

	<%= f.label :email %>
	<%= f.text_field :email %><br />

	<%= f.label :password %>
	<%= f.password_field :password %><br />

	<%= f.submit "Log in" %>

<% end %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg%></li>
		<%end%>
	</ul>
	<%= f.label :firstname %>
	<%= f.text_field :firstname %><br />

	<%= f.label :lastname %>
	<%= f.text_field :lastname %><br />

	<%= f.label :email %>
	<%= f.text_field :email %><br />

	<%= f.label :password %>
	<%= f.password_field :password %><br />

	<%= f.label :country %>
	<%= f.text_field :country %><br />

	<%= f.label :city %>
	<%= f.text_field :city %><br />

	<%= f.label :hous_number %>
	<%= f.text_field :hous_number %><br />

	<%= f.submit "Save" %>

<% end %>

app/views/users/show.html.erb
Firstname: <%= @user.firstname %>
</br>
Lastname: <%= @user.lastname %>
</br>
Country: <%= @user.country%>
</br>
City: <%= @user.city%>
</br>
Housnumber: <%= @user.hous_number%>
</br>
<%= link_to "Logout", user_path, method: :delete %>